{
	"items" :      [
		{	"label" : "United States",
			"type" :  "Country",
            "continent" : "NORTH AMERICA",
            "goldMedal" : "36",
            "silverMedal" : "38",
            "bronzeMedal" : "36",
            "totalMedal" : "110"
		},
		{	"label" : "China",
			"type" :  "Country",
            "continent" : "ASIA",
            "goldMedal" : "51",
            "silverMedal" : "21",
            "bronzeMedal" : "28",
            "totalMedal" : "100"
		},
		{	"label" : "Russia",
			"type" :  "Country",
            "continent" : "EUROPE",
            "goldMedal" : "23",
            "silverMedal" : "21",
            "bronzeMedal" : "29",
            "totalMedal" : "73"
		},
		{	"label" : "Great Britain",
			"type" :  "Country",
            "continent" : "EUROPE",
            "goldMedal" : "19",
            "silverMedal" : "13",
            "bronzeMedal" : "15",
            "totalMedal" : "47"
		},
		{	"label" : "Australia",
			"type" :  "Country",
            "continent" : "AUSTRALIA",
            "goldMedal" : "14",
            "silverMedal" : "15",
            "bronzeMedal" : "17",
            "totalMedal" : "46"
		},
		{	"label" : "France",
			"type" :  "Country",
            "continent" : "EUROPE",
            "goldMedal" : "7",
            "silverMedal" : "16",
            "bronzeMedal" : "18",
            "totalMedal" : "41"
		},
		{	"label" : "Germany",
			"type" :  "Country",
            "continent" : "EUROPE",
            "goldMedal" : "16",
            "silverMedal" : "10",
            "bronzeMedal" : "15",
            "totalMedal" : "41"
		},
		{	"label" : "South Korea",
			"type" :  "Country",
            "continent" : "ASIA",
            "goldMedal" : "13",
            "silverMedal" : "10",
            "bronzeMedal" : "8",
            "totalMedal" : "31"
		},
		{	"label" : "Ukraine",
			"type" :  "Country",
            "continent" : "EUROPE",
            "goldMedal" : "7",
            "silverMedal" : "5",
            "bronzeMedal" : "15",
            "totalMedal" : "27"
		},
		{	"label" : "Italy",
			"type" :  "Country",
            "continent" : "EUROPE",
            "goldMedal" : "8",
            "silverMedal" : "9",
            "bronzeMedal" : "10",
            "totalMedal" : "27"
		},
		{	"label" : "Japan",
			"type" :  "Country",
            "continent" : "ASIA",
            "goldMedal" : "9",
            "silverMedal" : "6",
            "bronzeMedal" : "10",
            "totalMedal" : "25"
		},
		{	"label" : "Cuba",
			"type" :  "Country",
            "continent" : "SOUTH AMERICA",
            "goldMedal" : "2",
            "silverMedal" : "11",
            "bronzeMedal" : "11",
            "totalMedal" : "24"
		},
		{	"label" : "Belarus",
			"type" :  "Country",
            "continent" : "EUROPE",
            "goldMedal" : "4",
            "silverMedal" : "5",
            "bronzeMedal" : "10",
            "totalMedal" : "19"
		},
		{	"label" : "Canada",
			"type" :  "Country",
            "continent" : "NORTH AMERICA",
            "goldMedal" : "3",
            "silverMedal" : "9",
            "bronzeMedal" : "6",
            "totalMedal" : "18"
		},
		{	"label" : "Spain",
			"type" :  "Country",
            "continent" : "EUROPE",
            "goldMedal" : "5",
            "silverMedal" : "10",
            "bronzeMedal" : "3",
            "totalMedal" : "18"
		},
		{	"label" : "Netherlands",
			"type" :  "Country",
            "continent" : "EUROPE",
            "goldMedal" : "7",
            "silverMedal" : "5",
            "bronzeMedal" : "4",
            "totalMedal" : "16"
		},
		{	"label" : "Brazil",
			"type" :  "Country",
            "continent" : "SOUTH AMERICA",
            "goldMedal" : "3",
            "silverMedal" : "4",
            "bronzeMedal" : "8",
            "totalMedal" : "15"
		},
		{	"label" : "Kenya",
			"type" :  "Country",
            "continent" : "AFRICA",
            "goldMedal" : "6",
            "silverMedal" : "4",
            "bronzeMedal" : "4",
            "totalMedal" : "14"
		},
		{	"label" : "Kazakhstan",
			"type" :  "Country",
            "continent" : "ASIA",
            "goldMedal" : "2",
            "silverMedal" : "4",
            "bronzeMedal" : "7",
            "totalMedal" : "13"
		},
		{	"label" : "Jamaica",
			"type" :  "Country",
            "continent" : "NORTH AMERICA",
            "goldMedal" : "6",
            "silverMedal" : "3",
            "bronzeMedal" : "2",
            "totalMedal" : "11"
		}
		]
	}