{
    "items" :      [
        {
            "adjacencies": {"0":"Robert Fano", "1":"Piotr Indyk", "2":"Alan Edelman","3":"Shafi Goldwasser","4":"Michel Goemans"},
            "photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/rivest.jpg",
            "url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=48",
            "uri" :       "http://128.30.44.24/Ronald+Rivest",
            "last-name" : "Rivest",
            "position" :  "faculty",
            "floor" :     "6th floor",
            "office" :    "32-G692",
            "phone" :     "253-5880",
            "email" :     "rivest@mit.edu",
            "type" :      "Person",
            "tower" :     "Gates",
            "label" :     "Ronald Rivest",
            "group" :     "cryptography and information security group"
        },
        {
            "adjacencies": {"0":"Ronald Rivest", "1":"Piotr Indyk", "2":"Alan Edelman","3":"Shafi Goldwasser","4":"Michel Goemans"},
            "photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/fano.jpg",
            "url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=14",
            "uri" :       "http://128.30.44.24/Robert+Fano",
            "last-name" : "Fano",
            "position" :  "professor emeritus",
            "floor" :     "6th floor",
            "office" :    "32-G616",
            "phone" :     "253-6021",
            "retired" :   "yes",
            "email" :     "fano@csail.mit.edu",
            "type" :      "Person",
            "tower" :     "Gates",
            "label" :     "Robert Fano",
            "group" :     "unknown"
        },
        {
            "adjacencies": {"0":"Robert Fano", "1":"Ronald Rivest", "2":"Alan Edelman","3":"Shafi Goldwasser","4":"Michel Goemans"},
            "photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/indyk.jpg",
            "url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=806",
            "uri" :       "http://128.30.44.24/Piotr+Indyk",
            "last-name" : "Indyk",
            "position" :  "associate professor",
            "floor" :     "6th floor",
            "office" :    "32-G642",
            "phone" :     "452-3402",
            "email" :     "indyk@csail.mit.edu",
            "type" :      "Person",
            "tower" :     "Gates",
            "label" :     "Piotr Indyk",
            "group" :     [
                "algorithms",
                "database group"
            ]
        },
        {
            "adjacencies": {"0":"Robert Fano", "1":"Piotr Indyk", "2":"Ronald Rivest","3":"Shafi Goldwasser","4":"Michel Goemans"},
            "photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/edelman.jpg",
            "url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=75",
            "uri" :       "http://128.30.44.24/Alan+Edelman",
            "last-name" : "Edelman",
            "position" :  "faculty",
            "floor" :     "6th floor",
            "office" :    "32-G606",
            "phone" :     "253-1355",
            "email" :     "edelman@csail.mit.edu",
            "type" :      "Person",
            "tower" :     "Gates",
            "label" :     "Alan Edelman",
            "group" :     "unknown"
        },
        {
            "adjacencies": {"0": "Saman Amarasinghe", "1":"Michael Ernst", "2":"Anant Agarwal","3":"Krste Asanovic"},
            "photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/miller.jpg",
            "url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=1525",
            "uri" :       "http://128.30.44.24/Rob+Miller",
            "last-name" : "Miller",
            "position" :  "associate professor",
            "floor" :     "7th floor",
            "office" :    "32-G716",
            "phone" :     "324-6028",
            "email" :     "rcm@csail.mit.edu",
            "type" :      "Person",
            "tower" :     "Gates",
            "label" :     "Rob Miller",
            "group" :     "user interface design group"
        },
        {
            "adjacencies": {"0":"Robert Fano", "1":"Piotr Indyk", "2":"Alan Edelman","3":"Ronald Rivest","4":"Michel Goemans"},
            "photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/goldwasser.jpg",
            "url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=17",
            "uri" :       "http://128.30.44.24/Shafi+Goldwasser",
            "last-name" : "Goldwasser",
            "position" :  "faculty",
            "floor" :     "6th floor",
            "office" :    "32-G682",
            "phone" :     "253-5914",
            "email" :     "shafi@csail.mit.edu",
            "type" :      "Person",
            "tower" :     "Gates",
            "label" :     "Shafi Goldwasser",
            "group" :     [
                "complexity theory group",
                "cryptography and information security group"
            ]
        },
        {
            "adjacencies": {"0": "Saman Amarasinghe", "1":"Rob Miller", "2":"Anant Agarwal","3":"Krste Asanovic"},
            "photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/ernst.jpg",
            "url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=757",
            "uri" :       "http://128.30.44.24/Michael+Ernst",
            "last-name" : "Ernst",
            "position" :  "associate professor",
            "floor" :     "7th floor",
            "office" :    "32-G718",
            "phone" :     "253-0945",
            "email" :     "mernst@csail.mit.edu",
            "type" :      "Person",
            "tower" :     "Gates",
            "label" :     "Michael Ernst",
            "group" :     "program analysis group"
        },
        {
            "adjacencies": {"0": "Saman Amarasinghe", "1":"Michael Ernst", "2":"Rob Miller","3":"Krste Asanovic"},
            "photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/agarwal.jpg",
            "url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=161",
            "uri" :       "http://128.30.44.24/Anant+Agarwal",
            "last-name" : "Agarwal",
            "position" :  "faculty",
            "floor" :     "7th floor",
            "office" :    "32-G782",
            "phone" :     "253-1448",
            "email" :     "agarwal@csail.mit.edu",
            "type" :      "Person",
            "tower" :     "Gates",
            "label" :     "Anant Agarwal",
            "group" :     "computer architecture group"
        },
        {
            "adjacencies": {"0": "Saman Amarasinghe", "1":"Michael Ernst", "2":"Anant Agarwal","3":"Rob Miller"},
            "photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/asanovic.jpg",
            "url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=235",
            "uri" :       "http://128.30.44.24/Krste+Asanovic",
            "last-name" : "Asanovic",
            "position" :  "associate professor",
            "floor" :     "7th floor",
            "office" :    "32-G776",
            "phone" :     "253-8081",
            "email" :     "krste@csail.mit.edu",
            "type" :      "Person",
            "tower" :     "Gates",
            "label" :     "Krste Asanovic",
            "group" :     "computer architecture group"
        },
        {
            "adjacencies": {"0":"Robert Fano", "1":"Piotr Indyk", "2":"Alan Edelman","3":"Shafi Goldwasser","4":"Ronald Rivest"},
            "photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/goemans.jpg",
            "url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=74",
            "uri" :       "http://128.30.44.24/Michel+Goemans",
            "last-name" : "Goemans",
            "position" :  "professor",
            "floor" :     "6th floor",
            "office" :    "32-G638",
            "phone" :     "253-2688",
            "email" :     "goemans@csail.mit.edu",
            "type" :      "Person",
            "tower" :     "Gates",
            "label" :     "Michel Goemans",
            "group" :     "algorithms"
        },
        {   "adjacencies" : {"0": "Alan Willsky", "1": "Eric Grimson", "2": "Daniel Weitzner", "3": "Jovan Popovic"},
            "photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/berger.jpg",
            "url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=3",
            "uri" :       "http://128.30.44.24/Bonnie+Berger",
            "last-name" : "Berger",
            "position" :  "faculty",
            "floor" :     "5th floor",
            "office" :    "32-G574",
            "phone" :     "253-1827",
            "email" :     "bab@csail.mit.edu",
            "type" :      "Person",
            "tower" :     "Gates",
            "label" :     "Bonnie Berger",
            "group" :     "computational biology group"
        },
        {   "adjacencies" : {"0": "Bonnie Berger", "1": "Alan Willsky", "2": "Daniel Weitzner", "3": "Jovan Popovic"},
            "photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/grimson.jpg",
            "url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2008",
            "uri" :       "http://128.30.44.24/Eric+Grimson",
            "last-name" : "Grimson",
            "position" :  "professor",
            "floor" :     "5th floor",
            "office" :    "32-D524",
            "phone" :     "253-5346",
            "email" :     "welg@csail.mit.edu",
            "type" :      "Person",
            "tower" :     "Dreyfoos",
            "label" :     "Eric Grimson",
            "group" :     [
                "medical vision group",
                "vision",
                "visual surveillance and monitoring group"
            ]
        },
        {   "adjacencies" : {"0": "Bonnie Berger", "1": "Eric Grimson", "2": "Alan Willsky", "3": "Jovan Popovic"},
            "photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/weitzner.jpg",
            "url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=479",
            "uri" :       "http://128.30.44.24/Daniel+Weitzner",
            "last-name" : "Weitzner",
            "position" :  "principal research scientist",
            "floor" :     "5th floor",
            "office" :    "32-G516",
            "phone" :     "253-8036",
            "email" :     "djweitzner@w3.org",
            "type" :      "Person",
            "tower" :     "Gates",
            "label" :     "Daniel Weitzner",
            "group" :     "decentralized information group"
        },
        {   "adjacencies" : {"0": "Bonnie Berger", "1": "Eric Grimson", "2": "Daniel Weitzner", "3": "Alan Willsky"},
            "photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/popovic.jpg",
            "url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=1175",
            "uri" :       "http://128.30.44.24/Jovan+Popovic",
            "last-name" : "Popovic",
            "position" :  "associate professor",
            "floor" :     "5th floor",
            "office" :    "32-D534",
            "phone" :     "452-3471",
            "email" :     "jovan@csail.mit.edu",
            "type" :      "Person",
            "tower" :     "Dreyfoos",
            "label" :     "Jovan Popovic",
            "group" :     "computer graphics group"
        },
        {   "adjacencies" : {"0": "Bonnie Berger", "1": "Eric Grimson", "2": "Daniel Weitzner", "3": "Jovan Popovic"},
            "photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/willsky.jpg",
            "url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2861",
            "uri" :       "http://128.30.44.24/Alan+Willsky",
            "last-name" : "Willsky",
            "position" :  "faculty",
            "floor" :     "5th floor",
            "office" :    "32-D582",
            "phone" :     "253-2356",
            "email" :     "willsky@mit.edu",
            "type" :      "Person",
            "tower" :     "Dreyfoos",
            "label" :     "Alan Willsky",
            "group" :     "stochastic systems group"
        },
        {   "adjacencies" : {"0": "John Fisher", "1": "Rodney Brooks", "2": "Ted Adelson", "3": "Polina Golland"},
            "photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/collins.jpg",
            "url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2000",
            "uri" :       "http://128.30.44.24/Michael+Collins",
            "last-name" : "Collins",
            "position" :  "faculty",
            "floor" :     "4th floor",
            "office" :    "32-G484",
            "phone" :     "253-0705",
            "email" :     "mcollins@csail.mit.edu",
            "type" :      "Person",
            "tower" :     "Gates",
            "label" :     "Michael Collins",
            "group" :     "unknown"
        },
        {   "adjacencies" : {"0": "Michael Collins", "1": "John Fisher", "2": "Ted Adelson", "3": "Polina Golland"},
            "photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/brooks.jpg",
            "url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2018",
            "uri" :       "http://128.30.44.24/Rodney+Brooks",
            "last-name" : "Brooks",
            "position" :  "director",
            "floor" :     "4th floor",
            "office" :    "32-G430",
            "phone" :     "253-5223",
            "email" :     "brooks@csail.mit.edu",
            "type" :      "Person",
            "tower" :     "Gates",
            "label" :     "Rodney Brooks",
            "group" :     "unknown"
        },
        {   "adjacencies" : {"0": "Michael Collins", "1": "Rodney Brooks", "2": "John Fisher", "3": "Polina Golland"},
            "photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/adelson.jpg",
            "url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2007",
            "uri" :       "http://128.30.44.24/Ted+Adelson",
            "last-name" : "Adelson",
            "position" :  "professor",
            "floor" :     "4th floor",
            "office" :    [
                "32-D424",
                "46-4115"
            ],
            "phone" :     "258-9501",
            "email" :     "adelson@csail.mit.edu",
            "type" :      "Person",
            "tower" :     "Dreyfoos",
            "label" :     "Ted Adelson",
            "group" :     "vision"
        },
        {   "adjacencies" : {"0": "Michael Collins", "1": "Rodney Brooks", "2": "Ted Adelson", "3": "John Fisher"},
            "photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/golland.jpg",
            "url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=1973",
            "uri" :       "http://128.30.44.24/Polina+Golland",
            "last-name" : "Golland",
            "position" :  "assistant professor",
            "floor" :     "4th floor",
            "office" :    "32-D470",
            "phone" :     "253-8005",
            "email" :     "polina@csail.mit.edu",
            "type" :      "Person",
            "tower" :     "Dreyfoos",
            "label" :     "Polina Golland",
            "group" :     [
                "medical vision group",
                "vision"
            ]
        },
        {   "adjacencies" : {"0": "Michael Collins", "1": "Rodney Brooks", "2": "Ted Adelson", "3": "Polina Golland"},
            "photo" :     "http://www.csail.mit.edu/biographies/PI/72dpi/fisher.jpg",
            "url" :       "http://www.csail.mit.edu/biographies/PI/bioprint.php?PeopleID=2019",
            "uri" :       "http://128.30.44.24/John+Fisher",
            "last-name" : "Fisher",
            "position" :  "principal research scientist",
            "floor" :     "4th floor",
            "office" :    "32-D468",
            "phone" :     "253-0788",
            "email" :     "fisher@csail.mit.edu",
            "type" :      "Person",
            "tower" :     "Dreyfoos",
            "label" :     "John Fisher",
            "group" :     [
                "vision",
                "vision interface group"
            ]
        }        
    ]
}